### ISSUE TITLE
reflection isn't working?

### ISSUE THREAD

**Issue by mganop** [husl-colors/husl-swift#1]
I've just installed the pod and was trying to use it in Xcode 7. I get the following error from line 42 in the Math.swift file:

```
let channels = reflect(Constant.m)
```

error:
'reflect' is unavailable: call the 'Mirror(reflecting:)' initializer.

Any thoughts on why this is happening?

**Comment by stphnclysmth** [comment]
Apparently, the syntax for reflection changed in Swift 2. It got first-class treatment with the new Mirror(reflecting:). The project has been updated to reflect that change (d480730).
