### ISSUE TITLE
swift package support [SPM]

### ISSUE THREAD

**Issue by JaydenIrwin** [husl-colors/husl-swift#11]
please add swift package manager support

**Comment by roryokane** [comment]
I’m just an HSLuv user who doesn’t know Swift, but I hope these links that may help to the maintainer in understanding this issue:

- [Swift.org - Package Manager](https://swift.org/package-manager/)
- [Swift Package Manager Documentation](https://github.com/apple/swift-package-manager/tree/master/Documentation)

It sounds like the process of making a package involves creating a `Package.swift` file, which should “[define] the package's name and its contents using the `PackageDescription` module.”

**Comment by robotive** [comment]
@JaydenIrwin @roryokane My PR #14 adds support for SPM. Thought looking at the other PR which is 16 days old it doesn't look like there is much activity going on here… so go figure when it might be merged. Will try to ping the maintainers thought.

**Comment by boronine** [comment]
@JaydenIrwin your wish has been granted. Courtesy of @robotive!
